### ISSUE TITLE
issue found  below image and I think there is need of add services option not availble

### ISSUE THREAD

**Issue by pravin234** [MahmudulHassan5809/car-wash-website#2]
![image](https://user-images.githubusercontent.com/17727435/100589727-7bd9c380-3319-11eb-9b90-d580ff71b47b.png)
Fatal error: Uncaught Error: Class 'Carbon\Carbon' not found in C:\xampp\htdocs\project\CarWashApp\admin\messages.php:69 Stack trace: #0 {main} thrown in C:\xampp\htdocs\project\CarWashApp\admin\messages.php on line 69

**Comment by MahmudulHassan5809** [comment]
Please install carbon.
Here is the link https://github.com/briannesbitt/Carbon

You can easily install it using composer. Hope it will help you.

Thanks and Regards
Mahmudul Hassan
