### ISSUE TITLE
autoloader issue

### ISSUE THREAD

**Issue by danielkaranja0** [MahmudulHassan5809/car-wash-website#3]
Okay I haven't worked with JS before and am finding it difficult to understand the issue of autoloader. Kindly advice on how to get rid of this error.
![Capture](https://user-images.githubusercontent.com/61149775/113776639-ca1d2a00-9732-11eb-87d3-d6a1fdd9d6b7.PNG)

**Comment by MahmudulHassan5809** [comment]
Please install package using composer.

**Comment by danielkaranja0** [comment]
Okay thanks. I did install but am finding it hard to login using your email already in the database for the admin part. kindly share the password coz I guess the email is clear. only the password is hashed.

**Comment by MahmudulHassan5809** [comment]
Hello . You can create an admin from PHPMyAdmin .just give md5 in the password field.
